# Snakemake SLURM profile

executor: slurm

# while monitoring your jobs, you may wonder how to make the JobName in sacct not a random string but the rule name
# no real way.  snakemake authors have instead added rule name as Comment field to sacct
# Comment does not show in default sacct call.  so, call sacct in an informative way like so:
#sacct --format=JobID,JobName,Comment,Account,State,Elapsed,ExitCode

jobs: 96                                # Maximum number of parallel jobs
max-jobs-per-second: 5                  # Limit new job submissions per second (cluster-friendly)
latency-wait: 45                        # Wait for file system to catch up after job completion
keep-going: false                       # Stop the workflow on rule failures
notemp: true                            # Retain temp files
default-resources:                      # Set these for all rules, unless overridden
  - mem_mb=10240
  - runtime=1440
  - slurm_account=jvmorr0
  - threads=1 
